.\" Process this file with
.\" groff -man -Tascii cqrprop.1
.\"
.TH cqrprop 1 "MAY 2011" Linux "User Manuals"
.SH NAME 
cqrprop \- Shows propagation data provided by Paul, N0NBH
.SH DESCRIPTION
.B cqrprop
shows image data provided by Paul, N0NBH on his website http://www.hamqsl.com/solar.html
.SH BUGS
Please report bug to email <petr at ok2cqr.com>
.SH AUTHOR
Petr Hlozek, OK2CQR <petr at ok2cqr.com>
